server:
  #the port on which our server works
  port: 5000

  #the maximum number of connections
  # allowed at the same time
  max_number_connection: 100

#memory_for_allocate allows us to
# allocate memory at the start of
# our program's launch, in order
# to have full control over memory
# (5GiB by default, defined in MiB)
memory_for_allocate: 5242880

#number_of_worker defines the number
# of parallel processes within the
# system (the default number follows
# the number of slabs)
number_of_worker: 15

# enables us to arbitrarily define
# our own number of slabs in the
# memory and the length of the bar
# itself
custom_slabs:
  # - chunk_capacity: 64
  #   max_allocate_memory: 0
  # - chunk_capacity: 128
  #   max_allocate_memory: 0
